
INSERT INTO "BOOK_RIDE"("ACCEPT_THE_RIDE","BOOK_RIDE_ID","DISTANCE_IN_KM","fare_in$","DESTINATION_LOCATION","DURATION","PICK_UP_LOCATION","REQUEST_DRIVERU")VALUES(false,11,0,0,'','','', '');
INSERT INTO "WALLET"("MONEY","WALLET_ID")VALUES(100, 11);
INSERT INTO "PASSENGER"("BOOK_RIDE_ID","IS_TEEN_ACCOUNT","ON_RIDE","PASSENGER_ID","WALLET_ID","PHONE_NUMBER","EMAIL","GENDER","NAME","PASSWORD","ROLE")VALUES(11,false,false,11,11,1234567890,'hetul@gmail.com','male','hetul','$2a$10$s/8B1BmXsfXNG7CQbZMtzuwBcCI8G.VfuSgIpPPFOvvFyKGoH7RKO','ROLE_USER');


INSERT INTO "BOOK_RIDE"("ACCEPT_THE_RIDE","BOOK_RIDE_ID","DISTANCE_IN_KM","fare_in$","DESTINATION_LOCATION","DURATION","PICK_UP_LOCATION","REQUEST_DRIVERU")VALUES(false,22,0,0,'','','', '');
INSERT INTO "WALLET"("MONEY","WALLET_ID")VALUES(200, 22);
INSERT INTO "PASSENGER"("BOOK_RIDE_ID","IS_TEEN_ACCOUNT","ON_RIDE","PASSENGER_ID","WALLET_ID","PHONE_NUMBER","EMAIL","GENDER","NAME","PASSWORD","ROLE")VALUES(22,false,false,22,22,7891234567,'seemant@gmail.com','male','seemant','$2a$10$UNnxCIE/60mfBQmdJyPJOOQRwCm85bVewkOHmXStBg.4uSmTly6iu','ROLE_USER');



INSERT INTO "BOOK_RIDE"("ACCEPT_THE_RIDE","BOOK_RIDE_ID","DISTANCE_IN_KM","fare_in$","DESTINATION_LOCATION","DURATION","PICK_UP_LOCATION","REQUEST_DRIVERU")VALUES(false,33,0,0,'','','', '');
INSERT INTO "WALLET"("MONEY","WALLET_ID")VALUES(300, 33);
INSERT INTO "PASSENGER"("BOOK_RIDE_ID","IS_TEEN_ACCOUNT","ON_RIDE","PASSENGER_ID","WALLET_ID","PHONE_NUMBER","EMAIL","GENDER","NAME","PASSWORD","ROLE")VALUES(33,false,false,33,33,7894561230,'rohan@gmail.com','male','rohan','$2a$10$tgkWybC3oeaNK7YMNPEk6uXyFzQLR0QaJLU7YWKleqWfiO5ioH4Aq','ROLE_USER');



INSERT INTO "BOOK_RIDE"("ACCEPT_THE_RIDE","BOOK_RIDE_ID","DISTANCE_IN_KM","fare_in$","DESTINATION_LOCATION","DURATION","PICK_UP_LOCATION","REQUEST_DRIVERU")VALUES(false,44,0,0,'','','', '');
INSERT INTO "WALLET"("MONEY","WALLET_ID")VALUES(100, 44);
INSERT INTO "PASSENGER"("BOOK_RIDE_ID","IS_TEEN_ACCOUNT","ON_RIDE","PASSENGER_ID","WALLET_ID","PHONE_NUMBER","EMAIL","GENDER","NAME","PASSWORD","ROLE")VALUES(44,false,false,44,44,4561237890,'manik@gmail.com','male','manik','$2a$10$C6/BypTrM4JjVzkcsXmb9uSHL4gxRa6OrlAcbbYA2ZzKTZpW32g0i','ROLE_USER');
